spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Настройки администратора
admin:
  credentials:
    login: admin
    password: My$PetProjectAdm1n!2025

jwt:
  secret: "hy8N0Kef4oDqa+rou6ObTkLBuJooXYbW"
  lifetime: 86400000

encryption:
  aes:
    # 44 random symbols
    key: "A4V8jJ2RnqW3v6xO9yPfB1uLmZcKp0HsDwEeNbRtCgY="