spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: ${database.default.login}
    password: ${database.default.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

example:
  app:
    secret: ${token.default.secret}
    lifetime: ${token.default.lifetime}