# you must fill these fields. Don't commit the file

database:
  default:
    login: your_bd_login
    password: your_bd_password

admin:
  default:
    login: your_admin_login
    password: your_admin_password

token:
  default:
    secret: your_secret
    lifetime: your_lifetime

aes:
  default:
    key: your_32_bit_key_for_card_encrypt