spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: your_bd_username
    password: your_bd_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# admin settings
admin:
  credentials:
    login: your_admin_login
    password: your_admin_password

# spring security
jwt:
  secret: "your_random_jwt_secret"
  lifetime: 86400000

# encryption secrets
encryption:
  aes:
    # 16, 24 or 32 random symbols
    key: "your_random_encryption_key"
    # 16 random symbols
    iv: "your_random_encryption_iv"